### ISSUE TITLE
FileExistsError: [Errno 17] File exists: '/home/rupesh/rupesh/colabfold/ecoli_aspartate_aminotransferase.fasta'

### ISSUE THREAD

**Issue by rupesh-sinha** [sokrypton/ColabFold#314] opened 2022-10-08 21:34 UTC
I recently installed colabfold following https://github.com/YoshitakaMo/localcolabfold

The program seems to be installed perfectly when checked with `colabfold_batch --help

I wanted to predict structure of a protein which I am providing it in input argument like:

$ colabfold_batch --amber --templates --num-recycle 3 --use-gpu-relax input /home/rupesh/rupesh/colabfold/ecoli_aspartate_aminotransferase.fasta

but received following error:

Traceback (most recent call last):
File "/home/rupesh/colabfold_batch/colabfold-conda/bin/colabfold_batch", line 8, in
sys.exit(main())
File "/home/rupesh/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/colabfold/batch.py", line 1703, in main
setup_logging(Path(args.results).joinpath("log.txt"))
File "/home/rupesh/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/colabfold/utils.py", line 44, in setup_logging
log_file.parent.mkdir(exist_ok=True, parents=True)
File "/home/rupesh/colabfold_batch/colabfold-conda/lib/python3.7/pathlib.py", line 1273, in mkdir
self._accessor.mkdir(self, mode)
FileExistsError: [Errno 17] File exists: '/home/rupesh/rupesh/colabfold/ecoli_aspartate_aminotransferase.fasta'

What is the reason for this error. Similar error appeared when I was trying to specify output directory with results
$ colabfold_batch --amber --templates --num-recycle 3 --use-gpu-relax input /home/rupesh/Desktop/ecoli_aspartate_aminotransferase.fasta results /home/rupesh/rupesh/fastq_aqua/

Error;

usage: colabfold_batch [-h] [--stop-at-score STOP_AT_SCORE]
[--stop-at-score-below STOP_AT_SCORE_BELOW]
[--num-recycle NUM_RECYCLE]
[--num-ensemble NUM_ENSEMBLE]
[--random-seed RANDOM_SEED] [--num-models {1,2,3,4,5}]
[--recompile-padding RECOMPILE_PADDING]
[--model-order MODEL_ORDER] [--host-url HOST_URL]
[--data DATA]
[--msa-mode {MMseqs2 UniRef+Environmental),MMseqs2 (UniRef only,single_sequence}]
[--model-type {auto,AlphaFold2-ptm,AlphaFold2-multimer-v1,AlphaFold2-multimer-v2}]
[--amber] [--templates]
[--custom-template-path CUSTOM_TEMPLATE_PATH] [--env]
[--cpu] [--rank {auto,plddt,ptmscore,multimer}]
[--pair-mode {unpaired,paired,unpaired+paired}]
[--recompile-all-models]
[--sort-queries-by {none,length,random}]
[--save-single-representations]
[--save-pair-representations] [--training]
[--max-msa {512:5120,512:1024,256:512,128:256,64:128,32:64,16:32}]
[--zip] [--use-gpu-relax]
[--overwrite-existing-results]
input results
colabfold_batch: error: unrecognized arguments: results /home/rupesh/rupesh/fastq_aqua/

Please help!

**Comment by YoshitakaMo** [comment] 2022-10-09 15:11
Duplicate of https://github.com/YoshitakaMo/localcolabfold/issues/112

**Closed** 2022-10-10 02:00 UTC
