### ISSUE TITLE
multimer prediction error in colabfold_batch (local & colab)

### ISSUE THREAD

**Issue by hz424** [sokrypton/ColabFold#97] opened 2021-11-22 20:01 UTC
I tried colabfold_batch for complex prediction using colabfold_batch local and colab. Both returned the following error.

Input sequences was 
">test_complex
MGIQGGSVLFGLLLVLAVFCHSGHSLQCYNCPNPTADCKTAVNCSSDFDACLITKAGLQV
YNKCWKFEHCNFNDVTTRLRENELTYYCCKKDLCNFNEQLENGGTSLSEKTVLLLVTPFL
AAAWSLHP:MKTKQNIARKLSRVVLLSTLVLSSAAPISAAFAETPTKPKAAQTEKKTEKKPENSNSEAA
KKALNDYIWGLQYDKLNILTHQGEKLKNHSSREAFHRPGEYVVIEKKKQSISNATSKLSV
SSANDDRIFPGALLKADQSLLENLPTLIPVNRGKTTISVNLPGLKNGESNLTVENPSNST
VRTAVNNLVEKWIQNYSKTHAVPARMQYESISAQSMSQLQAKFGADFSKVGAPLNVDFSS
VHKGEKQVFIANFRQVYYTASVDSPNSPSALFGSGITPTDLINRGVNSKTPPVYVSNVSY
GRAMYVKFETTSKSTKVQAAIDAVVKGAKLKAGTEYENILKNTKITAVVLGGNPGEASKV
ITGNIDTLKDLIQKGSNFSAQSPAVPISYTTSFVKDNSIATIQNNTDYIETKVTSYKDGA
LTLNHDGAFVARFYVYWEELGHDADGYETIRSRSWSGNGYNRGAHYSTTLRFKGNVRNIR
VKVLGATGLAWEPWRLIYSKNDLPLVPQRNISTWGTTLHPQFEDKVVKDNTD"

2021-11-22 14:32:44,973 Could not predict test_complex: Invalid character in the sequence: :
Traceback (most recent call last):
  File "/workdir/users/hz424/miniconda3/envs/colabfold/lib/python3.8/site-packages/colabfold/batch.py", line 620, in run
    **pipeline.make_sequence_features(
  File "/workdir/users/hz424/miniconda3/envs/colabfold/lib/python3.8/site-packages/alphafold/data/pipeline.py", line 40, in make_sequence_features
    features['aatype'] = residue_constants.sequence_to_onehot(
  File "/workdir/users/hz424/miniconda3/envs/colabfold/lib/python3.8/site-packages/alphafold/common/residue_constants.py", line 580, in sequence_to_onehot
    raise ValueError(f'Invalid character in the sequence: {aa_type}')
ValueError: Invalid character in the sequence: :
Traceback (most recent call last):
  File "/workdir/users/hz424/miniconda3/envs/colabfold/bin/colabfold_batch", line 8, in <module>
    sys.exit(main())
  File "/workdir/users/hz424/miniconda3/envs/colabfold/lib/python3.8/site-packages/colabfold/batch.py", line 842, in main
    run(
  File "/workdir/users/hz424/miniconda3/envs/colabfold/lib/python3.8/site-packages/colabfold/batch.py", line 645, in run
    np_example = features_for_chain[protein.PDB_CHAIN_IDS[0]]
KeyError: 'A'

**Comment by milot-mirdita** [comment] 2021-11-23 00:23
Are you running the latest git version of `colabfold_batch`?  Complex prediction from a FASTA file is supported only since this commit: https://github.com/sokrypton/ColabFold/commit/e1d5a42925d3f8e602afea97be16c089cb663d1b before that you would have to give a `.csv` file to `colabfold_batch`.

**Comment by hz424** [comment] 2021-11-23 14:16
My input was a directory with many heterodimer files (I tried both csv & fasta). It seems it does not process fasta file with more than one sequence for a directory input. or it will output "More than one sequence in {file}, ignoring all but the first sequence". https://github.com/sokrypton/ColabFold/blob/5ecd3a8327708ae1838febba68799d4d7ae263cf/colabfold/batch.py#L311-L324

**Comment by konstin** [comment] 2021-11-23 15:25
For fasta, create a directory with one fasta file per sequence. csv however shouldn't have that problem. Could you post the complete log (or upload `log.txt` from the result folder)?

**Comment by hz424** [comment] 2021-11-23 15:40
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-11-4ae5aa2603bd> in <module>()
     13 
     14 setup_logging(Path(result_dir).joinpath("log.txt"))
---> 15 queries, is_complex = get_queries(input_dir)
     16 run(
     17     queries=queries,

1 frames
/usr/local/lib/python3.7/dist-packages/colabfold/batch.py in get_queries(input_path, sort_queries_by)
    314             if not file.is_file():
    315                 continue
--> 316             (seqs, header) = pipeline.parsers.parse_fasta(file.read_text())
    317             if len(seqs) == 0:
    318                 logger.error(f"{file} is empty")

The "log.txt" file is empty.

/usr/local/lib/python3.7/dist-packages/alphafold/data/parsers.py in parse_fasta(fasta_string)
     87     elif not line:
     88       continue  # Skip blank lines.
---> 89     sequences[index] += line
     90 
     91   return sequences, descriptions

IndexError: list index out of range

Here is what I ran.
<img width="597" alt="Screen Shot 2021-11-23 at 10 37 05 AM" src="https://user-images.githubusercontent.com/35861163/143054914-71d30d72-889b-40c7-90c6-3e210453847c.png">

One of csv files I have in the directory. 
[Q9HD34_P0A6A8.csv](https://github.com/sokrypton/ColabFold/files/7589224/Q9HD34_P0A6A8.csv)

**Comment by konstin** [comment] 2021-11-23 15:46
Oh I see now what the problem is: We allow either a directory of fasta files or a single csv file as input, while you have a csv file in the directory, so trying to parse the csv as fasta fails. I added a fix in 360c57996e4df28f1878770821923f1056e2c4ed (not yet merged)

**Comment by hz424** [comment] 2021-11-23 15:52
Thanks for your fast reply. It is not clear how to use colabfold_batch for multimer prediction with fasta file in the README. Should it be linked by ":" for the sequences or multifasta file like in AF2-multimer?

**Comment by martin-steinegger** [comment] 2021-11-29 06:16
@hz424 combine the sequences with `:` in the fasta file to do a multimer prediction using the `colabfold_batch` cli.

**Closed** 2021-12-20 08:18 UTC
