### ISSUE TITLE
convert_pdb_to_mmcif will cause some custom templates to be ignored

### ISSUE THREAD

**Issue by jkosinski** [sokrypton/ColabFold#449] opened 2023-05-17 13:35 UTC
Here
https://github.com/sokrypton/ColabFold/blob/074aa2bbc0093b10e70ef632708f131d02a7aa7f/colabfold/batch.py#L202
you use biopython to convert PDB to CIF. Note however that biopython sets its own label_asym_id starting from chain A and puts the original PDB chain id as auth_asym_id. In case the custom template does not start chains from A, this mismatch will cause KeyErrors down the line when matching hhsearch results with template chain ids e.g. for a PDB template with chains B and C the output cif would get label_asym_id chain ids A, B resulting in:

```
2023-05-17 15:04:59,533 Could not get MSA/templates for Protein: 'C'
Traceback (most recent call last):
  File "/g/kosinski/kosinski/software/ColabFold/colabfold/batch.py", line 1364, in run
    = get_msa_and_templates(jobname, query_sequence, result_dir, msa_mode, use_templates,
  File "/g/kosinski/kosinski/software/ColabFold/colabfold/batch.py", line 773, in get_msa_and_templates
    template_feature = mk_template(
  File "/g/kosinski/kosinski/software/ColabFold/colabfold/batch.py", line 133, in mk_template
    templates_result = template_featurizer.get_templates(
  File "/g/kosinski/kosinski/software/AlphaFold_ColabFold/alphafold/alphafold/data/templates.py", line 886, in get_templates
    result = _process_single_hit(
  File "/g/kosinski/kosinski/software/AlphaFold_ColabFold/alphafold/alphafold/data/templates.py", line 731, in _process_single_hit
    parsing_result = mmcif_parsing.parse(
  File "/g/kosinski/kosinski/software/AlphaFold_ColabFold/alphafold/alphafold/data/mmcif_parsing.py", line 247, in parse
    author_chain = mmcif_to_author_chain_id[chain_id]
KeyError: 'C'
```

Those errors usually pass silently because by default errors are silently caught by mmcif_parsing.parse function. 

Maybe that explains why some users report templates are sometimes ignored.

**Comment by jkosinski** [comment] 2023-05-17 14:15
Thanks. A dream solution would be someone more experienced fixes that in BioPython and submits pull request there - I stumble on this bug repeatedly when using BioPython. In in the meantime, if you're not afraid evil dangerous hacks, this is my (or ChatGPT's) fix:

```
import inspect
import textwrap
from collections import defaultdict

from Bio.PDB.mmcifio import MMCIFIO

# Evil hack to get around the fact that BioPython doesn't allow you to set the chain ID when writing a structure to a mmCIF file
class MyMMCIFIO(MMCIFIO):
    def _save_structure(self, out_file, select, preserve_atom_numbering):
        code = inspect.getsource(MMCIFIO._save_structure)
        code = textwrap.dedent(code).replace("label_asym_id = self._get_label_asym_id(entity_id)", "label_asym_id = chain.id")
        exec(code, globals(), locals())
        return locals()['_save_structure'](self, out_file, select, preserve_atom_numbering)

```

**Comment by milot-mirdita** [comment] 2023-05-17 14:18
I think i can probably use the same hack I use to fix the hetatms

**Comment by milot-mirdita** [comment] 2023-05-23 05:43
It seems that this is a separate issue (not the one i was facing myself). Do you have an example sequence that triggers the problem?

**Comment by jkosinski** [comment] 2023-05-23 09:20
Or actually, probably the easiest: take any monomeric PDB structure with chain id that is not A, and try to model the same protein based on the structure as a custom template in the PDB format. With catch_all_errors: bool = False in mmcif_parsing.parse I would guess it would crash and with catch_all_errors: bool = True the template will be silently ignored.

**Comment by data2code** [comment] 2023-09-01 17:35
This does seem to fix the issue. I tested using the new code to convert PDB to CIF and then convert the CIF back to PDB, I am able to obtain the same PDB. Hope this will go into the original colabfold repository soon. Thanks!

**Comment by DimaMolod** [comment] 2023-09-29 12:59
I can confirm that. 
When I convert a pdb file to mmcif with mmcif chain ids 'A' and 'B' and author chain ids 'B' and 'C' and try to parse with alphafold.data.mmcif_parsing.parse I get a KeyError 'C' in ParsingResult.errors:
https://github.com/google-deepmind/alphafold/blob/main/alphafold/data/mmcif_parsing.py#L247
it happens because _get_protein_chains returns author ids instead of mmcif ids, and this is happening because _struct_asym.id in the mmcif file (converted from pdb by convert_pdb_to_mmcif) is pointing to the author chain ids, not to the internal ones:
https://github.com/google-deepmind/alphafold/blob/main/alphafold/data/mmcif_parsing.py#L353
Thanks for finding this and hope this fix will be merged to the main branch soon!

**Comment by jkosinski** [comment] 2023-09-29 14:30
@milot-mirdita yes - I think this is a good fix. label_seq_id and auth_seq_id can be different but then _struct_asym needs to point to label_seq_id.

**Closed** 2023-10-01 07:04 UTC
